services:
  frontend:
    image: romitkumar18/predictease-housing-price-prediction-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_BACKEND_URL=/api

  backend:
    image: romitkumar18/predictease-housing-price-prediction-backend:latest
    ports:
      - "5000:5000"
    depends_on:
      - ml-service
    environment:
      - PORT=5000
      - ML_SERVICE_URL=http://ml-service:8000

  ml-service:
    image: romitkumar18/predictease-housing-price-prediction-ml-service:latest
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
      - ml-service