services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
  frontend:
    build: ./frontend
    container_name: frontend
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend

  backend:
    build: ./backend
    container_name: backend
    environment:
      - PORT=5000
      - ML_SERVICE_URL=http://ml-service:8000

  ml-service:
    build: ./ml-service
    container_name: ml-service