services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:5000

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - ml-service
    environment:
      - PORT=5000
      - ML_SERVICE_URL=http://ml-service:8000

  ml-service:
    build: ./ml-service
    ports:
      - "8000:8000"