services:
  frontend:
    image: romitkumar18/predictease-housing-price-prediction-frontend:latest
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend
    depends_on:
      - backend

  backend:
    image: romitkumar18/predictease-housing-price-prediction-backend:latest
    environment:
      - PORT=5000
      - ML_SERVICE_URL=http://ml-service:8000
    depends_on:
      - ml-service

  ml-service:
    image: romitkumar18/predictease-housing-price-prediction-ml-service:latest

  nginx:
    image: romitkumar18/predictease-housing-price-prediction-nginx:latest
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
      - ml-service
