global:
  scrape_interval: 15s
  remote_write:
  - url: https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push
    basic_auth:
      username: <instance_id>
      password: <api_key>

scrape_configs:
  - job_name: 'app-metrics'
    static_configs:
      - targets: ['host.docker.internal:YOUR_METRICS_PORT']
