- name: deploy application on ecs ec2
  hosts: ecs_instance
  become: yes
  tasks:
    - name: Install Docker
      yum:
        name: docker
        state: present
    
    - name: Start Docker Service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install docker-compose
      shell: |
        sudo curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
      args:
        creates: /usr/local/bin/docker-compose

    - name: Copy docker-compose.yml
      copy:
        src: ../docker-compose.yml
        dest: /home/ec2-user/docker-compose.yml

    - name: Start Containers
      shell: |
        /usr/local/bin/docker-compose up -d
      args:
        chdir: /home/ec2-user/